NDefines.NGame.END_DATE = "1848.1.2"

NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 25
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 50
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -100
NDefines.NDiplomacy.CELESTIAL_EMPIRE_DEFAULT_INFLUENCE = 50
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.18
NDefines.NDiplomacy.GREAT_POWER_SUBJECT_CONTRIBUTION = 1.0
NDefines.NDiplomacy.REFUSED_CALL_FROM_TRIBUTARY_MANDATE_LOSS = 0
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 1
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.ANNUL_TREATIES_YEARS = 20
NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = 0

NDefines.NDiplomacy.TRIBUTE_BASE_CASH = 0.1						-- Tributary State: Part of yearly income given in tribute #They pay vassal fee
NDefines.NDiplomacy.TRIBUTE_BASE_ADM = 0.06					-- Tributary State: Part Adm tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_DIP = 0.06						-- Tributary State: Part Dip tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_BASE_MIL = 0.06						-- Tributary State: Base Mil tribute, mulitplied by total development
NDefines.NDiplomacy.TRIBUTE_MAX_MONARCH_POWER = 12.0				-- Tributary State: Max Adm/Dip/Mil per Tributary
NDefines.NDiplomacy.TRIBUTE_BASE_MANPOWER = 0.33					-- Tributary State: Part of yearly manpower given in tribute

NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 3000
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.35
NDefines.NCountry.BASE_POSSIBLE_POLICIES = 5
NDefines.NCountry.BASE_FREE_POLICIES = 2
NDefines.NCountry.FREE_IDEA_GROUP_COST  = 7
NDefines.NCountry.PS_BUY_IDEA = 250
NDefines.NCountry.BREAK_TRIBUTARY_STABILITY_PENALTY = 0
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 2
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 0.5
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.01
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.CONCENTRATE_DEVELOPMENT_DEVELOPMENT_DECREASE = 0
NDefines.NCountry.PILLAGE_CAPITAL_DEVELOPMENT_DECREASE = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 15
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.PS_MOVE_TRADE_PORT = 50
NDefines.NCountry.MAX_TOLERANCE_HERETIC = 5
NDefines.NCountry.MAX_TOLERANCE_HEATHEN = 5
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 10
NDefines.NCountry.MONARCH_DEATH_LEADER_STABILITY_PENALTY = 0
NDefines.NCountry.NAT_FOCUS_YEARS = 10
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.5
NDefines.NCountry.PS_ATTACK_NATIVES = 1
NDefines.NCountry.PS_GARRISON_SORTIES = 5
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 0
NDefines.NCountry.SPLENDOR_ABILITY_COST = 1000
NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 5
NDefines.NCountry.SCRIPTED_ADVISOR_DISCOUNT = 0.75
NDefines.NCountry.IDEA_TO_TECH = -0.01			-- percentage on tech reduction per idea.
NDefines.NCountry.PARLIAMENT_DEBATE_DURATION = 5
NDefines.NCountry.NUM_PARLIAMENT_ISSUES = 10
NDefines.NCountry.PARLIAMENT_BACKING_PERCENTAGE = 50
NDefines.NCountry.PS_BUY_GENERAL = 25
NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 30.0

NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 4 --4 Privileges for each estate


NDefines.NMilitary.CAVALRY_COST = 50.0
NDefines.NMilitary.ARTILLERY_COST = 50.0
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0.10
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.10
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
NDefines.NMilitary.SLACKEN_AP_DROP = 0.1
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1.0 -- 2.0 is vanilla
NDefines.NMilitary.WARGOAL_MAX_BONUS = 35
NDefines.NMilitary.MERCENARY_COMPANY_ARMY_TRADITION = 25
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.2
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 40
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 5
NDefines.NMilitary.STACKWIPE_MANPOWER_RETURN_FRACTION = 0.1

NDefines.NMilitary.CAWA_STARTING_STRENGTH = 1
NDefines.NMilitary.CREATE_CAWA_MIL_COST = 5
NDefines.NMilitary.CAWA_USES_CONSTRUCTION = 1

NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 5

NDefines.NMilitary.ASSAULT_WIDTH_LIMIT = 5						-- how many times the garrison size that can effectively assault at the same time.
NDefines.NMilitary.ASSAULT_ATTACKER_LOSS = 1.0 					-- MDEF_ASSAULT_ATTACKER_LOSS = 10,
NDefines.NMilitary.ASSAULT_DEFENDER_LOSS = 0.05 					-- _MDEF_ASSAULT_DEFENDER_LOSS = 10,
NDefines.NMilitary.ASSAULT_DICE_MODIFIER = 5 						-- _MDEF_ASSAULT_DICE_MODIFIER_
NDefines.NMilitary.SIEGE_FORCE_NEEDED_MULTIPLIER = 0.334				-- x times garrison to be able to siege.
NDefines.NMilitary.GARRISON_SIZE = 3000 							-- GARRISON_SIZE
NDefines.NMilitary.FORTRESS_COST = 0.167							-- base fort cost

NDefines.NMilitary.ARMY_DRILL_YEARLY_DECAY = -2.4
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 6.0
NDefines.NMilitary.COMBAT_DICE_SIDE = 7
NDefines.NMilitary.STRAIT_CROSSING_PENALTY = -1

NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0

NDefines.NEconomy.TRADE_WIND_STRENGTH = 0
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = 0
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 15
NDefines.NEconomy.PIRATES_TRADE_POWER_FACTOR = 0.1
NDefines.NEconomy.LARGE_COLONIAL_NATION_LIMIT = 15
NDefines.NEconomy.PRIVATEER_INCOME_COLLECTION_EFF = 0.1
NDefines.NEconomy.CARAVAN_FACTOR = 10
NDefines.NEconomy.CARAVAN_POWER_MAX = 20
NDefines.NEconomy.CARAVAN_POWER_MIN = 1
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 10
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 3
NDefines.NEconomy.TRADE_POWER_HOME_BONUS = 0.2

NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 20
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 25.0
NDefines.NGovernment.EXPAND_ADMIN_COST = 50
NDefines.NGovernment.YEARLY_TRIBAL_ALLEGIANCE_MAX = 0
NDefines.NGovernment.TRIBAL_ALLEGIANCE_HUMILIATE = 60.0
NDefines.NGovernment.TRIBAL_FEDERATION_ABILITY_COST = 50
NDefines.NGovernment.LEADER_AS_MONARCH_TRADITION = 50
NDefines.NGovernment.ENLIST_GENERAL_TRADITION = 50
NDefines.NGovernment.CONSCRIPT_FROM_TRIBES_TIME = 0
NDefines.NGovernment.CONSCRIPT_FROM_TRIBES_AMOUNT = 10
NDefines.NGovernment.YEARLY_TRIBAL_ALLEGIANCE_MAX = 0

NDefines.NAI.DEVELOPMENT_CAP_BASE = 30
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 30
NDefines.NAI.ACCEPTABLE_FRACTION_OF_INTEREST_PAYMENTS = 0.4
NDefines.NAI.MIN_CAV_PERCENTAGE = 0
NDefines.NAI.MAX_CAV_PERCENTAGE = 100
NDefines.NAI.DEVELOP_IN_SUBJECTS_PREFERENCE = 1
NDefines.NAI.SUBSIDY_YEARS = -1
NDefines.NAI.MIN_INCOME_FOR_SUBSIDIES = -1
NDefines.NAI.PS_SHORT_TERM_POOL = 10
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 1
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 1
NDefines.NAI.BIGSHIP_FRACTION = 0.1
NDefines.NAI.ARTILLERY_FRACTION = 0.1
NDefines.NAI.TRANSPORT_FRACTION = 0.2
NDefines.NAI.INCOME_SAVINGS_FRACTION = -1
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 0.1
NDefines.NAI.MILITARISE_FORT_BUDGET_FACTOR = 0.1
NDefines.NAI.DESIRED_SURPLUS = 0.01
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.05
NDefines.NAI.MAX_SAVINGS = -1
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.9
NDefines.NAI.STATE_MAINTENANCE_BUDGET_FRACTION = 0.1
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.1
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.1
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.6
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.1
NDefines.NAI.FORT_BUDGET_FRACTION = 0.1
NDefines.NAI.PEACE_TIME_MONTHS = 24
NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0
NDefines.NAI.PEACE_WARGOAL_FACTOR = 0.5
NDefines.NAI.PEACE_CAPITAL_FACTOR = 20
NDefines.NAI.PEACE_ALLY_WARSCORE_MULT = 1
NDefines.NAI.PEACE_ALLY_WARGOAL_MULT = 2
NDefines.NAI.PEACE_ALLY_CAPITAL_MULT = 1
NDefines.NAI.PEACE_DESPERATION_FACTOR = 20
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 0
NDefines.NAI.DIPLOMATIC_ACTION_CRUSADE_DEVELOPMENT_FACTOR = 10
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 200
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 0.0
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 10
NDefines.NAI.DRILLING_BUDGET_OF_SURPLUS = 0.01
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 1
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 10000
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 50.0
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = -1
NDefines.NAI.CALL_ECUMENICAL_COUNCIL_BASE_AI_DESIRE = -1
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 1
NDefines.NAI.ESTATE_PRIVILEGE_GRANT_THRESHOLD = 0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 0
NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4


NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = -1
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 0.3
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 0.3

NDefines.NGui.AUTO_SELECT_EVENT_MONTHS = 6

